### ISSUE TITLE
话说你做的东西怎么玩，也没有github-page

### ISSUE THREAD

**Issue by xcsweb** [gavin103/gotrans#1]

**Comment by xcsweb** [comment]
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\Users\Administrator\Desktop\ee\gotrans\node_modules\_pup
peteer@1.4.0@puppeteer\lib\NavigatorWatcher.js:73:21)
    at <anonymous>

**Comment by xcsweb** [comment]
node app.js 报错。。。超时。。。。

**Comment by pzy2020** [comment]
我install包之后，在node app.js报错和你的也不一样哦 。我的是：
const trans = async ()=>{
                    ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
